### ISSUE TITLE
DFD Comments October 4

### ISSUE THREAD

**Issue by germonprez** [csansoni/ISQA3420Assignment1#17]
Here are some pretty minor issues: 

1) Between the Developer and the Software Package DB, Software Package License and Vulnerability Results --should be-->Software Package License and Vulnerability Information

2) Going into Accept and Verify Project Results, Software Package License and Vulnerability Information --should be--> Software Project License and Vulnerability Information

That's it. These are very minor things. Well done. 

MG

**Comment by csansoni** [comment]
Completed, thanks!
